spring.application.name=ghibliapi

feign.encode.encoder-class=org.springframework.openfeign.support.SpringEncoder

stability.api.baseurl=https://api.stability.ai
stability.api.key=sk-YOUR_REAL_STABILITY_API_KEY_HERE